import React, { ReactNode } from "react";
import "./benefits.css";
import SectionHeader from "./heading";
import { FaRegMoneyBillAlt } from "react-icons/fa";
import { BsGraphUpArrow } from "react-icons/bs";
import { MdSupportAgent, MdPrivacyTip, MdPlagiarism } from "react-icons/md";
import { BsGraphDownArrow } from "react-icons/bs";
import { TbRobotOff } from "react-icons/tb";

const BenefitsList: React.FunctionComponent<{
  icon: ReactNode;
  header: string;
  benefit: string;
}> = ({ icon, header, benefit }) => {
  return (
    <React.Fragment>
      <div className="list">
        <div className="list-content">
          <i className="benefit-icon">{icon}</i>
          <h3 className="benefit-header">{header}</h3>
          <p className="description">{benefit}</p>
        </div>
      </div>
    </React.Fragment>
  );
};

const Benefits: React.FunctionComponent = () => {
  return (
    <React.Fragment>
      <div className="section" id="benefits-section">
        <div className="benefits">
          <SectionHeader heading={`Benefits of writing with us`} />

          <div className="benefits-list">
            <BenefitsList
              icon={<BsGraphUpArrow />}
              header={`High Quality`}
              benefit={`Your papers will be written by highly trained experts, graduands of various reputable universities.
                         The experts follow instructions to the letter before passing the drafts to editors who ensure that every client's expectation has been met.  `}
            />
            <BenefitsList
              icon={<FaRegMoneyBillAlt />}
              header={`Value for Money`}
              benefit={`We are determined to ensure that our clients are highly satisfied and will get value for their money. 
                        We allow for revisions and chargebacks when clients are unsatisfied with the services offered.  `}
            />
            <BenefitsList
              icon={<MdSupportAgent />}
              header={`24/7 Live support`}
              benefit={`Our support team will always be available to reply to your texts and concerns quickly! `}
            />
            <BenefitsList
              icon={<MdPrivacyTip />}
              header={`Privacy and confidentiality`}
              benefit={`We understand the need to keep your information secure and out of reach to third parties. 
                        We will ensure that your information remains confidential. `}
            />
            <BenefitsList
              icon={<MdPlagiarism />}
              header={`Plagiarism-free`}
              benefit={`Plagiarism is one of the biggest academic sins in modern schooling environments. As a result, we take it as a serious matter and ensure that
                         our papers are original. We use several platforms, including Turnitin and PlagCheck, to ensure your papers are original. `}
            />
            <BenefitsList
              icon={<TbRobotOff />}
              header={`No ChatGPT`}
              benefit={`Recently, the world witnessed the emergence of ChatGPT and other text-generation tools that have affected academic writing. Content generated by 
                         these tools is considered plagiarism, which we take seriously. Be assured that your paper will be human-written and thoroughly checked against any text generation tools. `}
            />
            <BenefitsList
              icon={<BsGraphDownArrow />}
              header={`Low Prices`}
              benefit={`We understand that numerous developments have negatively affected the global economy, including the recently witnessed 
                        coronavirus pandemic and the war in Ukraine. Motivated by this, we have adjusted our prices to ensure they are affordable for our customers, whom we value very much.  `}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  );
};
export default Benefits;
